# Generated by Django 4.0.4 on 2022-05-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_featured_image_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='projects/default.JPG', null=True, upload_to=''),
        ),
    ]
